default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

databases: &databases
  primary:
    <<: *default
    database: storage/<%= Rails.env %>.sqlite3
  cache:
    <<: *default
    database: storage/<%= Rails.env %>_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/<%= Rails.env %>_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/<%= Rails.env %>_cable.sqlite3
    migrations_paths: db/cable_migrate

development:
  <<: *databases

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *databases
